title: "Ayush Batra"
author: ""
description: ""
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"


# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md", title: "Home"}
  - {file: "blog.md"}
  - {file: "contact.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:ayushbatra2411@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/ayushbatra"}
  - {title: Github2, icon: github, url: "https://www.linkedin.com/in/ayush-batra-497a43192/"}
  # - {title: Linkedin, icon: linkedin, url: "https://www.linkedin.com/in/ayush-batra-497a43192/"}
  # - {title: Subscribe, icon: rss, url: "https://www.linkedin.com/in/ayush-batra-497a43192/"}
  # - {title: Subscribe, icon: rss, url: "/feed.xml"}


comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
